//
// lenet.ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void conv_backward_ispc(int32_t outC, int32_t inC, int32_t inH, int32_t inW, int32_t kH, int32_t kW, int32_t outH, int32_t outW, double * input, double * output, double * out_error, double * in_error, double * weight, double * dweight, double * dbias);
    extern void conv_forward_ispc(int32_t outC, int32_t inC, int32_t inH, int32_t inW, int32_t kH, int32_t kW, int32_t outH, int32_t outW, double * input, double * output, double * weight, double * bias);
    extern void dot_backward_ispc(int32_t inLen, int32_t outLen, double * input, double * output, double * out_error, double * in_error, double * weight, double * dweight, double * dbias);
    extern void dot_forward_ispc(int32_t inLen, int32_t outLen, double * input, double * output, double * weight, double * bias);
    extern void maxpool_backward_ispc(int32_t channels, int32_t inH, int32_t inW, int32_t outH, int32_t outW, double * out_error, double * in_error, int32_t * indices);
    extern void maxpool_forward_ispc(int32_t channels, int32_t inH, int32_t inW, int32_t outH, int32_t outW, int32_t poolSize, double * input, double * output, int32_t * indices);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
